//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAU_HINH_BAI_THI
    {
        public int ID { get; set; }
        public Nullable<int> ID_BAI_THI { get; set; }
        public Nullable<int> ID_LOAI_CAU_HOI { get; set; }
        public string SO_LUONG_CAU_DE { get; set; }
        public string SO_LUONG_CAU_TB { get; set; }
        public string SO_LUONG_CAU_KHO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
    
        public virtual BAI_THI BAI_THI { get; set; }
        public virtual LOAI_CAU_HOI LOAI_CAU_HOI { get; set; }
    }
}
