//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu1
    {
        public Menu1()
        {
            this.Menu_Quyen = new HashSet<Menu_Quyen>();
        }
    
        public int ID { get; set; }
        public int ID_LOAI_MENU { get; set; }
        public string TEN { get; set; }
        public string TEN_URL { get; set; }
        public string LINK { get; set; }
        public bool isEnabled { get; set; }
        public int ID_CHA { get; set; }
        public int STT { get; set; }
        public Nullable<int> ID_NGON_NGU { get; set; }
    
        public virtual ICollection<Menu_Quyen> Menu_Quyen { get; set; }
    }
}
