//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MENU_LOAI
    {
        public TBL_MENU_LOAI()
        {
            this.TBL_MENU = new HashSet<TBL_MENU>();
        }
    
        public int ID { get; set; }
        public string TIEU_DE { get; set; }
        public string MO_TA { get; set; }
        public string CODE { get; set; }
    
        public virtual ICollection<TBL_MENU> TBL_MENU { get; set; }
    }
}
