//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NGUOI_DUNG_QUYEN
    {
        public int ID { get; set; }
        public int ID_NGUOI_DUNG { get; set; }
        public int ID_QUYEN { get; set; }
    
        public virtual TBL_NGUOI_DUNG TBL_NGUOI_DUNG { get; set; }
    }
}
