//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DS_TAI_LIEU
    {
        public int ID { get; set; }
        public int ID_HE_THONG { get; set; }
        public Nullable<bool> DAC_TA_YCKH { get; set; }
        public Nullable<bool> GPKT { get; set; }
        public Nullable<bool> TL2589 { get; set; }
        public Nullable<bool> PTTK { get; set; }
        public Nullable<bool> HDSD { get; set; }
        public Nullable<bool> HDCDHT { get; set; }
        public Nullable<bool> UAT { get; set; }
        public Nullable<bool> CODING { get; set; }
        public Nullable<bool> BBNTKT { get; set; }
        public Nullable<bool> BBNTTT { get; set; }
        public Nullable<bool> BBBG_DBHD { get; set; }
        public Nullable<bool> HDBT { get; set; }
        public Nullable<bool> HDQLTD { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
    }
}
