//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NGUOI_DUNG_PHONG_BAN
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> isLeader { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
