//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HE_THONG
    {
        public TBL_HE_THONG()
        {
            this.TBL_HOP_DA = new HashSet<TBL_HOP_DA>();
            this.TBL_NHIEM_VU = new HashSet<TBL_NHIEM_VU>();
            this.TBL_RUI_RO = new HashSet<TBL_RUI_RO>();
        }
    
        public int ID { get; set; }
        public string MA_HE_THONG { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_HOP_DONG { get; set; }
        public string TEN { get; set; }
        public string MO_TA { get; set; }
        public Nullable<System.DateTime> NGAY_KH_GUI_YC { get; set; }
        public Nullable<System.DateTime> NGAY_KH_YC_HOAN_THANH { get; set; }
        public Nullable<int> ID_KH_KY_HD { get; set; }
        public Nullable<int> ID_KH_NSD { get; set; }
        public Nullable<short> DO_UU_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU_LAM { get; set; }
        public Nullable<System.DateTime> NGAY_NGHIEM_THU_TT { get; set; }
        public Nullable<short> QUY { get; set; }
        public Nullable<int> MAN_DAY { get; set; }
        public Nullable<int> ID_TRANG_THAI_DA { get; set; }
        public Nullable<int> ID_PRODUCT_OWNER { get; set; }
        public Nullable<int> ID_PM { get; set; }
        public Nullable<int> ID_NGUOI_THUC_HIEN { get; set; }
        public Nullable<int> ID_NGUOI_PHOI_HOP { get; set; }
        public Nullable<int> ID_LOAI_TRIEN_KHAI_DA { get; set; }
        public Nullable<int> ID_PHAM_VI_DA { get; set; }
        public Nullable<int> ID_TIEN_DO { get; set; }
        public Nullable<int> TT_DBHD { get; set; }
    
        public virtual ICollection<TBL_HOP_DA> TBL_HOP_DA { get; set; }
        public virtual ICollection<TBL_NHIEM_VU> TBL_NHIEM_VU { get; set; }
        public virtual ICollection<TBL_RUI_RO> TBL_RUI_RO { get; set; }
        public virtual TBL_HOP_DONG TBL_HOP_DONG { get; set; }
    }
}
