//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_THEO_DOI_CV
    {
        public int ID { get; set; }
        public string TEN_CONG_VIEC { get; set; }
        public Nullable<int> ID_HE_THONG { get; set; }
        public Nullable<int> ID_HOP_DONG { get; set; }
        public Nullable<int> ID_NGUOI_CHU_TRI { get; set; }
        public string ID_NGUOI_PHOI_HOP { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU { get; set; }
        public System.DateTime NGAY_KET_THUC { get; set; }
        public Nullable<int> ID_KET_QUA_CV { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_MUC_DO_CV { get; set; }
    }
}
