//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NHIEM_VU
    {
        public int ID { get; set; }
        public Nullable<int> ID_CHA { get; set; }
        public Nullable<int> ID_HE_THONG_DA { get; set; }
        public Nullable<int> ID_CHANGE_REQUEST { get; set; }
        public string TEN_NHIEM_VU { get; set; }
        public Nullable<int> ID_NGUOI_CHU_TRI { get; set; }
        public Nullable<int> ID_NGUOI_PHOI_HOP { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU_DK { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC_DK { get; set; }
        public Nullable<int> SO_NGAY_DK { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU_TT { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC_TT { get; set; }
        public Nullable<int> SO_NGAY_TT { get; set; }
        public Nullable<int> ID_KET_QUA { get; set; }
        public Nullable<int> PHAN_TRAM_KET_QUA { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> SPRINT { get; set; }
    
        public virtual TBL_HE_THONG TBL_HE_THONG { get; set; }
    }
}
