//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RUI_RO
    {
        public int ID { get; set; }
        public int ID_HE_THONG { get; set; }
        public string MA_RUI_RO { get; set; }
        public string NOI_DUNG { get; set; }
        public string MO_TA { get; set; }
        public string GIAI_PHAP { get; set; }
        public string KIEN_NGHI { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> ID_MUC_UU_TIEN { get; set; }
        public Nullable<int> ID_KET_QUA { get; set; }
        public Nullable<int> ID_NGUOI_CHU_TRI { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
        public Nullable<System.DateTime> NGAY_PHAT_SINH { get; set; }
        public Nullable<bool> TT_TRACH_NHIEM_KH { get; set; }
        public Nullable<bool> TT_TRACH_NHIEM_AITS { get; set; }
        public Nullable<bool> TT_TRACH_NHIEM_DT { get; set; }
    
        public virtual TBL_HE_THONG TBL_HE_THONG { get; set; }
    }
}
