//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HOP_DA
    {
        public int ID { get; set; }
        public int ID_HE_THONG { get; set; }
        public System.DateTime NGAY_HOP { get; set; }
        public Nullable<System.TimeSpan> GIO_BAT_DAU { get; set; }
        public Nullable<System.TimeSpan> GIO_KET_THUC { get; set; }
        public string DIA_DIEM { get; set; }
        public Nullable<int> ID_KIEU_HOP { get; set; }
        public Nullable<int> ID_HINH_THUC_HOP { get; set; }
        public string NOI_DUNG_HOP { get; set; }
        public string GHI_CHU { get; set; }
        public string URL { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
    
        public virtual TBL_HE_THONG TBL_HE_THONG { get; set; }
    }
}
