//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QUYEN
    {
        public TBL_QUYEN()
        {
            this.TBL_MENU_QUYEN = new HashSet<TBL_MENU_QUYEN>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CODE { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
    
        public virtual ICollection<TBL_MENU_QUYEN> TBL_MENU_QUYEN { get; set; }
    }
}
